const grade_percents = {
    "Project": 35,
    "Presentation": 5,
    "Homework": 25,
    "Midterm": 15,
    "Final": 20
}

// This is a subset of the Game Sales as of Dec 22 2016 dataset posted
// to Kaggle: https://www.kaggle.com/rush4ratio/video-game-sales-with-ratings/version/2
// It includes only titles listed with a 2015 year of release that
// have both user scores and critics scores.
const games = [
 {
   "Name": "Rugby 15",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Bigben Interactive",
   "NA_Sales": 0.03,
   "EU_Sales": 0.05,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.09,
   "Critic_Score": 20,
   "Critic_Count": 4,
   "User_Score": 3.1,
   "User_Count": 30,
   "Developer": "HB Studios Multimedia",
   "Rating": "E"
 },
 {
   "Name": "Gravity Falls: Legend of the Gnome Gemulets",
   "Platform": "3DS",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Ubisoft",
   "NA_Sales": 0.03,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.04,
   "Critic_Score": 46,
   "Critic_Count": 4,
   "User_Score": 5.8,
   "User_Count": 10,
   "Developer": "Ubisoft Osaka",
   "Rating": "E"
 },
 {
   "Name": "Guitar Hero Live",
   "Platform": "WiiU",
   "Year_of_Release": 2015,
   "Genre": "Misc",
   "Publisher": "Activision",
   "NA_Sales": 0.12,
   "EU_Sales": 0.05,
   "JP_Sales": 0,
   "Other_Sales": 0.02,
   "Global_Sales": 0.19,
   "Critic_Score": 84,
   "Critic_Count": 4,
   "User_Score": 6.1,
   "User_Count": 36,
   "Developer": "Activision, FreeStyleGames",
   "Rating": "T"
 },
 {
   "Name": "Xblaze: Lost Memories",
   "Platform": "PS3",
   "Year_of_Release": 2015,
   "Genre": "Adventure",
   "Publisher": "Arc System Works",
   "NA_Sales": 0.02,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.02,
   "Critic_Score": 63,
   "Critic_Count": 4,
   "User_Score": 6.2,
   "User_Count": 5,
   "Developer": "Arc System Works",
   "Rating": "M"
 },
 {
   "Name": "One Piece: Pirate Warriors 3",
   "Platform": "PSV",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0,
   "EU_Sales": 0.03,
   "JP_Sales": 0.13,
   "Other_Sales": 0.01,
   "Global_Sales": 0.17,
   "Critic_Score": 76,
   "Critic_Count": 4,
   "User_Score": 6.3,
   "User_Count": 17,
   "Developer": "Omega Force",
   "Rating": "T"
 },
 {
   "Name": "The Peanuts Movie: Snoopy's Grand Adventure",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Activision",
   "NA_Sales": 0,
   "EU_Sales": 0.02,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.03,
   "Critic_Score": 59,
   "Critic_Count": 4,
   "User_Score": 6.6,
   "User_Count": 19,
   "Developer": "Activision, Behaviour Interactive",
   "Rating": "E"
 },
 {
   "Name": "Sword Art Online: Lost Song",
   "Platform": "PSV",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0.06,
   "EU_Sales": 0.04,
   "JP_Sales": 0.23,
   "Other_Sales": 0.03,
   "Global_Sales": 0.36,
   "Critic_Score": 70,
   "Critic_Count": 4,
   "User_Score": 7.1,
   "User_Count": 27,
   "Developer": "Bandai Namco Games, Artdink",
   "Rating": "T"
 },
 {
   "Name": "Senran Kagura: Estival Versus",
   "Platform": "PSV",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Marvelous Interactive",
   "NA_Sales": 0.04,
   "EU_Sales": 0.02,
   "JP_Sales": 0.09,
   "Other_Sales": 0.02,
   "Global_Sales": 0.18,
   "Critic_Score": 71,
   "Critic_Count": 4,
   "User_Score": 7.4,
   "User_Count": 34,
   "Developer": "Marvelous Inc.",
   "Rating": "M"
 },
 {
   "Name": "Don Bradman Cricket 14",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Tru Blu Entertainment",
   "NA_Sales": 0.01,
   "EU_Sales": 0.09,
   "JP_Sales": 0,
   "Other_Sales": 0.02,
   "Global_Sales": 0.12,
   "Critic_Score": 76,
   "Critic_Count": 4,
   "User_Score": 7.4,
   "User_Count": 19,
   "Developer": "Big Ant Studios",
   "Rating": "E"
 },
 {
   "Name": "Rugby 15",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Bigben Interactive",
   "NA_Sales": 0.04,
   "EU_Sales": 0.06,
   "JP_Sales": 0,
   "Other_Sales": 0.02,
   "Global_Sales": 0.11,
   "Critic_Score": 19,
   "Critic_Count": 5,
   "User_Score": 3.4,
   "User_Count": 65,
   "Developer": "HB Studios Multimedia",
   "Rating": "E"
 },
 {
   "Name": "LEGO Dimensions",
   "Platform": "WiiU",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Warner Bros. Interactive Entertainment",
   "NA_Sales": 0.3,
   "EU_Sales": 0.18,
   "JP_Sales": 0,
   "Other_Sales": 0.05,
   "Global_Sales": 0.53,
   "Critic_Score": 62,
   "Critic_Count": 5,
   "User_Score": 6.5,
   "User_Count": 29,
   "Developer": "Traveller's Tales",
   "Rating": "E10+"
 },
 {
   "Name": "The Crew: Wild Run",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Ubisoft",
   "NA_Sales": 0,
   "EU_Sales": 0.02,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.02,
   "Critic_Score": 65,
   "Critic_Count": 5,
   "User_Score": 6.6,
   "User_Count": 21,
   "Developer": "Ivory Tower",
   "Rating": "T"
 },
 {
   "Name": "LEGO Jurassic World",
   "Platform": "WiiU",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Warner Bros. Interactive Entertainment",
   "NA_Sales": 0.27,
   "EU_Sales": 0.19,
   "JP_Sales": 0.02,
   "Other_Sales": 0.04,
   "Global_Sales": 0.52,
   "Critic_Score": 71,
   "Critic_Count": 5,
   "User_Score": 8.1,
   "User_Count": 14,
   "Developer": "TT Games",
   "Rating": "E10+"
 },
 {
   "Name": "Rugby World Cup 2015",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Ubisoft",
   "NA_Sales": 0,
   "EU_Sales": 0.05,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.06,
   "Critic_Score": 25,
   "Critic_Count": 6,
   "User_Score": 1.9,
   "User_Count": 39,
   "Developer": "HB Studios Multimedia",
   "Rating": "E"
 },
 {
   "Name": "Bladestorm: Nightmare",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Tecmo Koei",
   "NA_Sales": 0.03,
   "EU_Sales": 0.02,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.05,
   "Critic_Score": 48,
   "Critic_Count": 6,
   "User_Score": 7.1,
   "User_Count": 8,
   "Developer": "Omega Force",
   "Rating": "T"
 },
 {
   "Name": "The Crew: Wild Run",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Ubisoft",
   "NA_Sales": 0,
   "EU_Sales": 0.02,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.02,
   "Critic_Score": 74,
   "Critic_Count": 6,
   "User_Score": 7.4,
   "User_Count": 41,
   "Developer": "Ivory Tower",
   "Rating": "T"
 },
 {
   "Name": "Brothers: A Tale of Two Sons",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Adventure",
   "Publisher": "505 Games",
   "NA_Sales": 0.03,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.04,
   "Critic_Score": 81,
   "Critic_Count": 6,
   "User_Score": 8.9,
   "User_Count": 26,
   "Developer": "Starbreeze",
   "Rating": "T"
 },
 {
   "Name": "Rodea the Sky Soldier",
   "Platform": "3DS",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Nippon Ichi Software",
   "NA_Sales": 0.03,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.04,
   "Critic_Score": 45,
   "Critic_Count": 7,
   "User_Score": 5.6,
   "User_Count": 37,
   "Developer": "Prope, Kadokawa",
   "Rating": "E10+"
 },
 {
   "Name": "Just Dance 2016",
   "Platform": "WiiU",
   "Year_of_Release": 2015,
   "Genre": "Misc",
   "Publisher": "Ubisoft",
   "NA_Sales": 0.27,
   "EU_Sales": 0.25,
   "JP_Sales": 0,
   "Other_Sales": 0.05,
   "Global_Sales": 0.57,
   "Critic_Score": 73,
   "Critic_Count": 7,
   "User_Score": 6.9,
   "User_Count": 11,
   "Developer": "Ubisoft",
   "Rating": "E10+"
 },
 {
   "Name": "Valkyrie Drive: Bhikkhuni",
   "Platform": "PSV",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "PQube",
   "NA_Sales": 0,
   "EU_Sales": 0.03,
   "JP_Sales": 0.07,
   "Other_Sales": 0.01,
   "Global_Sales": 0.11,
   "Critic_Score": 72,
   "Critic_Count": 7,
   "User_Score": 8.5,
   "User_Count": 11,
   "Developer": "Marvelous Inc.",
   "Rating": "M"
 },
 {
   "Name": "Steins;Gate 0",
   "Platform": "PSV",
   "Year_of_Release": 2015,
   "Genre": "Adventure",
   "Publisher": "PQube",
   "NA_Sales": 0,
   "EU_Sales": 0.03,
   "JP_Sales": 0.05,
   "Other_Sales": 0.01,
   "Global_Sales": 0.09,
   "Critic_Score": 86,
   "Critic_Count": 7,
   "User_Score": 9.3,
   "User_Count": 20,
   "Developer": "5pb",
   "Rating": "M"
 },
 {
   "Name": "MX vs. ATV Supercross Encore",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Nordic Games",
   "NA_Sales": 0,
   "EU_Sales": 0.05,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.06,
   "Critic_Score": 42,
   "Critic_Count": 8,
   "User_Score": 4.1,
   "User_Count": 9,
   "Developer": "Rainbow Studios",
   "Rating": "E"
 },
 {
   "Name": "Ride",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Racing",
   "Publisher": "Milestone S.r.l.",
   "NA_Sales": 0,
   "EU_Sales": 0.03,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.03,
   "Critic_Score": 68,
   "Critic_Count": 8,
   "User_Score": 4.8,
   "User_Count": 30,
   "Developer": "Milestone S.r.l",
   "Rating": "E"
 },
 {
   "Name": "LEGO Jurassic World",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Warner Bros. Interactive Entertainment",
   "NA_Sales": 0,
   "EU_Sales": 0.04,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.04,
   "Critic_Score": 72,
   "Critic_Count": 8,
   "User_Score": 7.1,
   "User_Count": 31,
   "Developer": "TT Games",
   "Rating": "E10+"
 },
 {
   "Name": "Exist Archive: The Other Side of the Sky",
   "Platform": "PSV",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Aksys Games",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0.05,
   "Other_Sales": 0,
   "Global_Sales": 0.06,
   "Critic_Score": 71,
   "Critic_Count": 8,
   "User_Score": 8.3,
   "User_Count": 12,
   "Developer": "Tri-Ace",
   "Rating": "T"
 },
 {
   "Name": "Ride",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Racing",
   "Publisher": "Milestone S.r.l.",
   "NA_Sales": 0.04,
   "EU_Sales": 0.05,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.1,
   "Critic_Score": 54,
   "Critic_Count": 9,
   "User_Score": 5.3,
   "User_Count": 17,
   "Developer": "Milestone S.r.l",
   "Rating": "E"
 },
 {
   "Name": "Legend of Kay Anniversary",
   "Platform": "WiiU",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Nordic Games",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": 67,
   "Critic_Count": 9,
   "User_Score": 7.1,
   "User_Count": 35,
   "Developer": "Neon Studios, Kaiko",
   "Rating": "E10+"
 },
 {
   "Name": "Transformers: Devastation",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Activision",
   "NA_Sales": 0,
   "EU_Sales": 0.03,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.03,
   "Critic_Score": 74,
   "Critic_Count": 9,
   "User_Score": 7.6,
   "User_Count": 56,
   "Developer": "PlatinumGames",
   "Rating": "T"
 },
 {
   "Name": "Shovel Knight",
   "Platform": "3DS",
   "Year_of_Release": 2015,
   "Genre": "Platform",
   "Publisher": "Yacht Club Games",
   "NA_Sales": 0.08,
   "EU_Sales": 0.04,
   "JP_Sales": 0.02,
   "Other_Sales": 0.01,
   "Global_Sales": 0.14,
   "Critic_Score": 90,
   "Critic_Count": 9,
   "User_Score": 8.2,
   "User_Count": 225,
   "Developer": "Yacht Club Games",
   "Rating": "E"
 },
 {
   "Name": "Art Academy: Home Studio",
   "Platform": "WiiU",
   "Year_of_Release": 2015,
   "Genre": "Misc",
   "Publisher": "Nintendo",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": 82,
   "Critic_Count": 9,
   "User_Score": 8.3,
   "User_Count": 20,
   "Developer": "Headstrong Games",
   "Rating": "E"
 },
 {
   "Name": "The Book of Unwritten Tales 2",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Adventure",
   "Publisher": "Nordic Games",
   "NA_Sales": 0,
   "EU_Sales": 0.06,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.07,
   "Critic_Score": 63,
   "Critic_Count": 9,
   "User_Score": 8.6,
   "User_Count": 7,
   "Developer": "KING Art",
   "Rating": ""
 },
 {
   "Name": "FIFA 16",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Electronic Arts",
   "NA_Sales": 0.06,
   "EU_Sales": 0.13,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.2,
   "Critic_Score": 81,
   "Critic_Count": 10,
   "User_Score": 4.4,
   "User_Count": 296,
   "Developer": "EA Sports",
   "Rating": "E"
 },
 {
   "Name": "Mortal Kombat X",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Fighting",
   "Publisher": "Warner Bros. Interactive Entertainment",
   "NA_Sales": 0.01,
   "EU_Sales": 0.04,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.05,
   "Critic_Score": 76,
   "Critic_Count": 10,
   "User_Score": 5.1,
   "User_Count": 475,
   "Developer": "High Voltage Software",
   "Rating": "M"
 },
 {
   "Name": "Just Dance 2016",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Misc",
   "Publisher": "Ubisoft",
   "NA_Sales": 0.25,
   "EU_Sales": 0.04,
   "JP_Sales": 0,
   "Other_Sales": 0.03,
   "Global_Sales": 0.32,
   "Critic_Score": 66,
   "Critic_Count": 10,
   "User_Score": 6.1,
   "User_Count": 18,
   "Developer": "Ubisoft",
   "Rating": "E10+"
 },
 {
   "Name": "Just Dance 2016",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Misc",
   "Publisher": "Ubisoft",
   "NA_Sales": 0.17,
   "EU_Sales": 0.13,
   "JP_Sales": 0,
   "Other_Sales": 0.06,
   "Global_Sales": 0.36,
   "Critic_Score": 73,
   "Critic_Count": 10,
   "User_Score": 6.8,
   "User_Count": 20,
   "Developer": "Ubisoft",
   "Rating": "E10+"
 },
 {
   "Name": "Grand Ages: Medieval",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Strategy",
   "Publisher": "Kalypso Media",
   "NA_Sales": 0,
   "EU_Sales": 0.05,
   "JP_Sales": 0.02,
   "Other_Sales": 0.01,
   "Global_Sales": 0.07,
   "Critic_Score": 64,
   "Critic_Count": 10,
   "User_Score": 7.1,
   "User_Count": 12,
   "Developer": "Gaming Minds Studios",
   "Rating": "T"
 },
 {
   "Name": "Zombie Army Trilogy",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Shooter",
   "Publisher": "Rebellion Developments",
   "NA_Sales": 0.05,
   "EU_Sales": 0.05,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.11,
   "Critic_Score": 62,
   "Critic_Count": 10,
   "User_Score": 7.2,
   "User_Count": 40,
   "Developer": "Rebellion",
   "Rating": ""
 },
 {
   "Name": "Metal Gear Solid V: The Phantom Pain",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Konami Digital Entertainment",
   "NA_Sales": 0.41,
   "EU_Sales": 0.26,
   "JP_Sales": 0.01,
   "Other_Sales": 0.07,
   "Global_Sales": 0.75,
   "Critic_Score": 95,
   "Critic_Count": 10,
   "User_Score": 7.3,
   "User_Count": 900,
   "Developer": "Kojima Productions, Moby Dick Studio",
   "Rating": "M"
 },
 {
   "Name": "BlazBlue: Chrono Phantasma Extend",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "PQube",
   "NA_Sales": 0.07,
   "EU_Sales": 0.03,
   "JP_Sales": 0.02,
   "Other_Sales": 0.02,
   "Global_Sales": 0.14,
   "Critic_Score": 80,
   "Critic_Count": 10,
   "User_Score": 7.7,
   "User_Count": 31,
   "Developer": "Arc System Works",
   "Rating": "T"
 },
 {
   "Name": "Brothers: A Tale of Two Sons",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Adventure",
   "Publisher": "505 Games",
   "NA_Sales": 0.03,
   "EU_Sales": 0.08,
   "JP_Sales": 0,
   "Other_Sales": 0.02,
   "Global_Sales": 0.14,
   "Critic_Score": 81,
   "Critic_Count": 10,
   "User_Score": 8.6,
   "User_Count": 73,
   "Developer": "Starbreeze",
   "Rating": "T"
 },
 {
   "Name": "Destiny: The Taken King",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Shooter",
   "Publisher": "Activision",
   "NA_Sales": 0.85,
   "EU_Sales": 0.23,
   "JP_Sales": 0,
   "Other_Sales": 0.12,
   "Global_Sales": 1.19,
   "Critic_Score": 89,
   "Critic_Count": 11,
   "User_Score": 5.2,
   "User_Count": 393,
   "Developer": "Bungie Software, Bungie",
   "Rating": "T"
 },
 {
   "Name": "Grand Ages: Medieval",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Strategy",
   "Publisher": "Kalypso Media",
   "NA_Sales": 0,
   "EU_Sales": 0.05,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.05,
   "Critic_Score": 63,
   "Critic_Count": 11,
   "User_Score": 5.4,
   "User_Count": 52,
   "Developer": "Gaming Minds Studios",
   "Rating": "T"
 },
 {
   "Name": "Deadpool",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Activision",
   "NA_Sales": 0.14,
   "EU_Sales": 0.11,
   "JP_Sales": 0,
   "Other_Sales": 0.05,
   "Global_Sales": 0.29,
   "Critic_Score": 60,
   "Critic_Count": 11,
   "User_Score": 5.7,
   "User_Count": 68,
   "Developer": "High Moon Studios",
   "Rating": "M"
 },
 {
   "Name": "Borderlands: The Handsome Collection",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Shooter",
   "Publisher": "Take-Two Interactive",
   "NA_Sales": 0.26,
   "EU_Sales": 0.13,
   "JP_Sales": 0,
   "Other_Sales": 0.04,
   "Global_Sales": 0.43,
   "Critic_Score": 80,
   "Critic_Count": 11,
   "User_Score": 7.8,
   "User_Count": 119,
   "Developer": "Gearbox Software",
   "Rating": "M"
 },
 {
   "Name": "The Elder Scrolls Online",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Bethesda Softworks",
   "NA_Sales": 0.78,
   "EU_Sales": 0.38,
   "JP_Sales": 0,
   "Other_Sales": 0.12,
   "Global_Sales": 1.28,
   "Critic_Score": 77,
   "Critic_Count": 11,
   "User_Score": 8.4,
   "User_Count": 613,
   "Developer": "ZeniMax Media",
   "Rating": "M"
 },
 {
   "Name": "Grand Kingdom",
   "Platform": "PSV",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Nippon Ichi Software",
   "NA_Sales": 0.01,
   "EU_Sales": 0.01,
   "JP_Sales": 0.04,
   "Other_Sales": 0.01,
   "Global_Sales": 0.06,
   "Critic_Score": 76,
   "Critic_Count": 11,
   "User_Score": 8.8,
   "User_Count": 33,
   "Developer": "Spike Chunsoft",
   "Rating": "T"
 },
 {
   "Name": "Pro Evolution Soccer 2016",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Konami Digital Entertainment",
   "NA_Sales": 0,
   "EU_Sales": 0.04,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.04,
   "Critic_Score": 76,
   "Critic_Count": 12,
   "User_Score": 4.3,
   "User_Count": 286,
   "Developer": "Konami",
   "Rating": "E"
 },
 {
   "Name": "LEGO Dimensions",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Warner Bros. Interactive Entertainment",
   "NA_Sales": 0.22,
   "EU_Sales": 0.15,
   "JP_Sales": 0,
   "Other_Sales": 0.04,
   "Global_Sales": 0.41,
   "Critic_Score": 80,
   "Critic_Count": 12,
   "User_Score": 6.9,
   "User_Count": 27,
   "Developer": "Traveller's Tales",
   "Rating": "E10+"
 },
 {
   "Name": "Broken Sword 5: The Serpent's Curse",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Adventure",
   "Publisher": "Revolution Software",
   "NA_Sales": 0,
   "EU_Sales": 0.02,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.02,
   "Critic_Score": 77,
   "Critic_Count": 12,
   "User_Score": 7.2,
   "User_Count": 11,
   "Developer": "Revolution Software",
   "Rating": "T"
 },
 {
   "Name": "Resident Evil: Revelations 2",
   "Platform": "PSV",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Capcom",
   "NA_Sales": 0,
   "EU_Sales": 0.03,
   "JP_Sales": 0.07,
   "Other_Sales": 0.01,
   "Global_Sales": 0.1,
   "Critic_Score": 65,
   "Critic_Count": 12,
   "User_Score": 7.8,
   "User_Count": 63,
   "Developer": "Frima Studio",
   "Rating": "M"
 },
 {
   "Name": "F1 2015",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Racing",
   "Publisher": "Codemasters",
   "NA_Sales": 0,
   "EU_Sales": 0.05,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.05,
   "Critic_Score": 61,
   "Critic_Count": 13,
   "User_Score": 3.6,
   "User_Count": 63,
   "Developer": "Codemasters",
   "Rating": "E"
 },
 {
   "Name": "F1 2015",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Racing",
   "Publisher": "Codemasters",
   "NA_Sales": 0.08,
   "EU_Sales": 0.15,
   "JP_Sales": 0,
   "Other_Sales": 0.02,
   "Global_Sales": 0.25,
   "Critic_Score": 64,
   "Critic_Count": 13,
   "User_Score": 5.3,
   "User_Count": 22,
   "Developer": "Codemasters",
   "Rating": "E"
 },
 {
   "Name": "Skylanders: SuperChargers",
   "Platform": "WiiU",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Activision",
   "NA_Sales": 0.25,
   "EU_Sales": 0.19,
   "JP_Sales": 0,
   "Other_Sales": 0.04,
   "Global_Sales": 0.48,
   "Critic_Score": 87,
   "Critic_Count": 13,
   "User_Score": 5.6,
   "User_Count": 65,
   "Developer": "Vicarious Visions",
   "Rating": "E10+"
 },
 {
   "Name": "The Crew: Wild Run",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Ubisoft",
   "NA_Sales": 0,
   "EU_Sales": 0.08,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.1,
   "Critic_Score": 73,
   "Critic_Count": 13,
   "User_Score": 6.8,
   "User_Count": 50,
   "Developer": "Ivory Tower",
   "Rating": "T"
 },
 {
   "Name": "Wasteland 2",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Deep Silver",
   "NA_Sales": 0.04,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.05,
   "Critic_Score": 77,
   "Critic_Count": 13,
   "User_Score": 7.1,
   "User_Count": 56,
   "Developer": "InXile Entertainment",
   "Rating": "M"
 },
 {
   "Name": "Metal Gear Solid V: The Phantom Pain",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Konami Digital Entertainment",
   "NA_Sales": 0,
   "EU_Sales": 0.07,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.08,
   "Critic_Score": 91,
   "Critic_Count": 13,
   "User_Score": 7.7,
   "User_Count": 1963,
   "Developer": "Kojima Productions",
   "Rating": "M"
 },
 {
   "Name": "Exist Archive: The Other Side of the Sky",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Aksys Games",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0.03,
   "Other_Sales": 0,
   "Global_Sales": 0.04,
   "Critic_Score": 69,
   "Critic_Count": 13,
   "User_Score": 7.9,
   "User_Count": 16,
   "Developer": "Tri-Ace",
   "Rating": "T"
 },
 {
   "Name": "The Witcher 3: Wild Hunt",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0.69,
   "EU_Sales": 0.5,
   "JP_Sales": 0,
   "Other_Sales": 0.11,
   "Global_Sales": 1.31,
   "Critic_Score": 91,
   "Critic_Count": 13,
   "User_Score": 9.2,
   "User_Count": 3963,
   "Developer": "CD Projekt Red Studio",
   "Rating": "M"
 },
 {
   "Name": "Batman: Arkham Knight",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Warner Bros. Interactive Entertainment",
   "NA_Sales": 0.09,
   "EU_Sales": 0.03,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.13,
   "Critic_Score": 70,
   "Critic_Count": 14,
   "User_Score": 2.5,
   "User_Count": 1967,
   "Developer": "Rocksteady Studios, Iron Galaxy Studios",
   "Rating": "M"
 },
 {
   "Name": "Assassin's Creed Syndicate",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Ubisoft",
   "NA_Sales": 0.11,
   "EU_Sales": 0.09,
   "JP_Sales": 0,
   "Other_Sales": 0.02,
   "Global_Sales": 0.21,
   "Critic_Score": 74,
   "Critic_Count": 14,
   "User_Score": 5.9,
   "User_Count": 544,
   "Developer": "Ubisoft Quebec",
   "Rating": "M"
 },
 {
   "Name": "NBA 2K16",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Take-Two Interactive",
   "NA_Sales": 1.95,
   "EU_Sales": 0.15,
   "JP_Sales": 0,
   "Other_Sales": 0.24,
   "Global_Sales": 2.34,
   "Critic_Score": 86,
   "Critic_Count": 14,
   "User_Score": 6.2,
   "User_Count": 115,
   "Developer": "Visual Concepts",
   "Rating": "E10+"
 },
 {
   "Name": "Pro Evolution Soccer 2016",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Konami Digital Entertainment",
   "NA_Sales": 0.04,
   "EU_Sales": 0.06,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.11,
   "Critic_Score": 85,
   "Critic_Count": 14,
   "User_Score": 6.2,
   "User_Count": 144,
   "Developer": "Konami",
   "Rating": "E"
 },
 {
   "Name": "Broken Sword 5: The Serpent's Curse",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Adventure",
   "Publisher": "Revolution Software",
   "NA_Sales": 0,
   "EU_Sales": 0.06,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.07,
   "Critic_Score": 72,
   "Critic_Count": 14,
   "User_Score": 7.2,
   "User_Count": 23,
   "Developer": "Revolution Software",
   "Rating": "T"
 },
 {
   "Name": "Final Fantasy XIV: Heavensward",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Square Enix",
   "NA_Sales": 0.01,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.02,
   "Critic_Score": 86,
   "Critic_Count": 14,
   "User_Score": 7.7,
   "User_Count": 255,
   "Developer": "Square Enix",
   "Rating": "T"
 },
 {
   "Name": "War for the Overworld",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Strategy",
   "Publisher": "Unknown",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": 65,
   "Critic_Count": 14,
   "User_Score": 7.7,
   "User_Count": 90,
   "Developer": "Subterranean Games",
   "Rating": ""
 },
 {
   "Name": "Ray Gigant",
   "Platform": "PSV",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.04,
   "Other_Sales": 0,
   "Global_Sales": 0.04,
   "Critic_Score": 72,
   "Critic_Count": 14,
   "User_Score": 8.1,
   "User_Count": 25,
   "Developer": "Bandai Namco Games",
   "Rating": "T"
 },
 {
   "Name": "Toy Soldiers: War Chest",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Ubisoft",
   "NA_Sales": 0.05,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.06,
   "Critic_Score": 60,
   "Critic_Count": 14,
   "User_Score": 8.4,
   "User_Count": 50,
   "Developer": "Krome Studios",
   "Rating": ""
 },
 {
   "Name": "Skylanders: SuperChargers",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Activision",
   "NA_Sales": 0.17,
   "EU_Sales": 0.05,
   "JP_Sales": 0,
   "Other_Sales": 0.02,
   "Global_Sales": 0.24,
   "Critic_Score": 76,
   "Critic_Count": 15,
   "User_Score": 5.5,
   "User_Count": 17,
   "Developer": "Vicarious Visions",
   "Rating": "E10+"
 },
 {
   "Name": "Dynasty Warriors 8: Empires",
   "Platform": "PSV",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Tecmo Koei",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.02,
   "Other_Sales": 0,
   "Global_Sales": 0.02,
   "Critic_Score": 70,
   "Critic_Count": 15,
   "User_Score": 7.4,
   "User_Count": 9,
   "Developer": "Omega Force",
   "Rating": "T"
 },
 {
   "Name": "Mario vs. Donkey Kong: Tipping Stars",
   "Platform": "3DS",
   "Year_of_Release": 2015,
   "Genre": "Puzzle",
   "Publisher": "Nintendo",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.06,
   "Other_Sales": 0,
   "Global_Sales": 0.06,
   "Critic_Score": 70,
   "Critic_Count": 15,
   "User_Score": 7.5,
   "User_Count": 48,
   "Developer": "Nintendo, Nintendo Software Technology",
   "Rating": "E"
 },
 {
   "Name": "Project CARS",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Racing",
   "Publisher": "Slightly Mad Studios",
   "NA_Sales": 0.11,
   "EU_Sales": 0.13,
   "JP_Sales": 0,
   "Other_Sales": 0.02,
   "Global_Sales": 0.26,
   "Critic_Score": 81,
   "Critic_Count": 16,
   "User_Score": 5.8,
   "User_Count": 135,
   "Developer": "Slightly Mad Studios",
   "Rating": "E"
 },
 {
   "Name": "Saints Row: Gat out of Hell",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Deep Silver",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": 65,
   "Critic_Count": 16,
   "User_Score": 6,
   "User_Count": 27,
   "Developer": "Volition Inc.",
   "Rating": "M"
 },
 {
   "Name": "Pokemon Rumble World",
   "Platform": "3DS",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Nintendo",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0.08,
   "Other_Sales": 0,
   "Global_Sales": 0.09,
   "Critic_Score": 58,
   "Critic_Count": 16,
   "User_Score": 6.4,
   "User_Count": 69,
   "Developer": "Ambrella, The Pokemon Company",
   "Rating": "E10+"
 },
 {
   "Name": "Batman: Arkham Knight",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Warner Bros. Interactive Entertainment",
   "NA_Sales": 0.88,
   "EU_Sales": 0.47,
   "JP_Sales": 0,
   "Other_Sales": 0.14,
   "Global_Sales": 1.49,
   "Critic_Score": 85,
   "Critic_Count": 16,
   "User_Score": 6.6,
   "User_Count": 694,
   "Developer": "Rocksteady Studios",
   "Rating": "M"
 },
 {
   "Name": "The Sims 4: Get Together",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Simulation",
   "Publisher": "Electronic Arts",
   "NA_Sales": 0.05,
   "EU_Sales": 0.15,
   "JP_Sales": 0,
   "Other_Sales": 0.02,
   "Global_Sales": 0.22,
   "Critic_Score": 72,
   "Critic_Count": 16,
   "User_Score": 7.3,
   "User_Count": 117,
   "Developer": "Maxis",
   "Rating": "T"
 },
 {
   "Name": "NBA Live 16",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Electronic Arts",
   "NA_Sales": 0.09,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.11,
   "Critic_Score": 60,
   "Critic_Count": 17,
   "User_Score": 5.6,
   "User_Count": 62,
   "Developer": "EA Sports",
   "Rating": "E"
 },
 {
   "Name": "LEGO Jurassic World",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Warner Bros. Interactive Entertainment",
   "NA_Sales": 0.38,
   "EU_Sales": 0.22,
   "JP_Sales": 0,
   "Other_Sales": 0.06,
   "Global_Sales": 0.65,
   "Critic_Score": 70,
   "Critic_Count": 17,
   "User_Score": 6.7,
   "User_Count": 44,
   "Developer": "TT Games",
   "Rating": "E10+"
 },
 {
   "Name": "Tropico 5",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Simulation",
   "Publisher": "Kalypso Media",
   "NA_Sales": 0.06,
   "EU_Sales": 0.16,
   "JP_Sales": 0.06,
   "Other_Sales": 0.04,
   "Global_Sales": 0.31,
   "Critic_Score": 76,
   "Critic_Count": 17,
   "User_Score": 7.1,
   "User_Count": 110,
   "Developer": "Haemimont",
   "Rating": "T"
 },
 {
   "Name": "Steins;Gate 0",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Adventure",
   "Publisher": "PQube",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.05,
   "Other_Sales": 0,
   "Global_Sales": 0.05,
   "Critic_Score": 81,
   "Critic_Count": 17,
   "User_Score": 8.3,
   "User_Count": 29,
   "Developer": "5pb",
   "Rating": "M"
 },
 {
   "Name": "Tony Hawk's Pro Skater 5",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Activision",
   "NA_Sales": 0.09,
   "EU_Sales": 0.02,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.12,
   "Critic_Score": 39,
   "Critic_Count": 18,
   "User_Score": 2.1,
   "User_Count": 132,
   "Developer": "Robomodo",
   "Rating": "T"
 },
 {
   "Name": "WWE 2K16",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Take-Two Interactive",
   "NA_Sales": 0.32,
   "EU_Sales": 0.22,
   "JP_Sales": 0,
   "Other_Sales": 0.05,
   "Global_Sales": 0.59,
   "Critic_Score": 72,
   "Critic_Count": 18,
   "User_Score": 5.7,
   "User_Count": 75,
   "Developer": "Yuke's",
   "Rating": "T"
 },
 {
   "Name": "NHL 16",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Electronic Arts",
   "NA_Sales": 0.38,
   "EU_Sales": 0.05,
   "JP_Sales": 0,
   "Other_Sales": 0.05,
   "Global_Sales": 0.48,
   "Critic_Score": 80,
   "Critic_Count": 18,
   "User_Score": 6,
   "User_Count": 81,
   "Developer": "EA Sports, EA Canada",
   "Rating": "E10+"
 },
 {
   "Name": "Dragon Ball: XenoVerse",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Fighting",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0.18,
   "EU_Sales": 0.11,
   "JP_Sales": 0,
   "Other_Sales": 0.03,
   "Global_Sales": 0.32,
   "Critic_Score": 67,
   "Critic_Count": 18,
   "User_Score": 7.2,
   "User_Count": 128,
   "Developer": "Dimps Corporation",
   "Rating": "T"
 },
 {
   "Name": "Shovel Knight",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Platform",
   "Publisher": "Yacht Club Games",
   "NA_Sales": 0.03,
   "EU_Sales": 0.03,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.08,
   "Critic_Score": 90,
   "Critic_Count": 18,
   "User_Score": 7.6,
   "User_Count": 312,
   "Developer": "Yacht Club Games",
   "Rating": "E"
 },
 {
   "Name": "God Eater Resurrection",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.08,
   "Other_Sales": 0,
   "Global_Sales": 0.08,
   "Critic_Score": 70,
   "Critic_Count": 18,
   "User_Score": 7.8,
   "User_Count": 44,
   "Developer": "Shift, Bandai Namco Games",
   "Rating": "T"
 },
 {
   "Name": "Shantae and the Pirate's Curse",
   "Platform": "3DS",
   "Year_of_Release": 2015,
   "Genre": "Platform",
   "Publisher": "Rising Star Games",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0.03,
   "Other_Sales": 0,
   "Global_Sales": 0.04,
   "Critic_Score": 82,
   "Critic_Count": 18,
   "User_Score": 8.5,
   "User_Count": 86,
   "Developer": "WayForward",
   "Rating": "E10+"
 },
 {
   "Name": "Toy Soldiers: War Chest",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Ubisoft",
   "NA_Sales": 0.06,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.07,
   "Critic_Score": 62,
   "Critic_Count": 19,
   "User_Score": 7.7,
   "User_Count": 61,
   "Developer": "Krome Studios",
   "Rating": ""
 },
 {
   "Name": "Animal Crossing: Amiibo Festival",
   "Platform": "WiiU",
   "Year_of_Release": 2015,
   "Genre": "Misc",
   "Publisher": "Nintendo",
   "NA_Sales": 0.19,
   "EU_Sales": 0.11,
   "JP_Sales": 0.09,
   "Other_Sales": 0.03,
   "Global_Sales": 0.41,
   "Critic_Score": 46,
   "Critic_Count": 20,
   "User_Score": 4.4,
   "User_Count": 173,
   "Developer": "Nintendo, Nd Cube",
   "Rating": "E"
 },
 {
   "Name": "Final Fantasy XIV: Heavensward",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Square Enix",
   "NA_Sales": 0,
   "EU_Sales": 0.06,
   "JP_Sales": 0.06,
   "Other_Sales": 0.01,
   "Global_Sales": 0.13,
   "Critic_Score": 86,
   "Critic_Count": 20,
   "User_Score": 7.6,
   "User_Count": 225,
   "Developer": "Square Enix",
   "Rating": "T"
 },
 {
   "Name": "Guitar Hero Live",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Misc",
   "Publisher": "Activision",
   "NA_Sales": 0.3,
   "EU_Sales": 0.2,
   "JP_Sales": 0,
   "Other_Sales": 0.05,
   "Global_Sales": 0.55,
   "Critic_Score": 81,
   "Critic_Count": 21,
   "User_Score": 5.1,
   "User_Count": 69,
   "Developer": "FreeStyleGames",
   "Rating": "T"
 },
 {
   "Name": "Fairy Fencer F: Advent Dark Force",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Idea Factory International",
   "NA_Sales": 0.02,
   "EU_Sales": 0,
   "JP_Sales": 0.05,
   "Other_Sales": 0,
   "Global_Sales": 0.07,
   "Critic_Score": 71,
   "Critic_Count": 21,
   "User_Score": 6.2,
   "User_Count": 34,
   "Developer": "Compile Heart",
   "Rating": "T"
 },
 {
   "Name": "Mortal Kombat X",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Fighting",
   "Publisher": "Warner Bros. Interactive Entertainment",
   "NA_Sales": 1.03,
   "EU_Sales": 0.21,
   "JP_Sales": 0,
   "Other_Sales": 0.14,
   "Global_Sales": 1.38,
   "Critic_Score": 86,
   "Critic_Count": 21,
   "User_Score": 7.3,
   "User_Count": 279,
   "Developer": "Warner Bros. Interactive Entertainment, NetherRealm Studios",
   "Rating": "M"
 },
 {
   "Name": "Assassin's Creed Syndicate",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Ubisoft",
   "NA_Sales": 0.62,
   "EU_Sales": 0.56,
   "JP_Sales": 0,
   "Other_Sales": 0.11,
   "Global_Sales": 1.3,
   "Critic_Score": 78,
   "Critic_Count": 22,
   "User_Score": 6.1,
   "User_Count": 402,
   "Developer": "Ubisoft Quebec",
   "Rating": "M"
 },
 {
   "Name": "Legend of Kay Anniversary",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Nordic Games",
   "NA_Sales": 0,
   "EU_Sales": 0.02,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.03,
   "Critic_Score": 62,
   "Critic_Count": 22,
   "User_Score": 6.4,
   "User_Count": 11,
   "Developer": "Neon Studios, Kaiko",
   "Rating": "E10+"
 },
 {
   "Name": "Resident Evil: Revelations 2",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Capcom",
   "NA_Sales": 0.07,
   "EU_Sales": 0.02,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.1,
   "Critic_Score": 75,
   "Critic_Count": 22,
   "User_Score": 7.5,
   "User_Count": 106,
   "Developer": "Capcom",
   "Rating": "M"
 },
 {
   "Name": "Madden NFL 16",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Electronic Arts",
   "NA_Sales": 2.08,
   "EU_Sales": 0.08,
   "JP_Sales": 0,
   "Other_Sales": 0.26,
   "Global_Sales": 2.42,
   "Critic_Score": 84,
   "Critic_Count": 23,
   "User_Score": 6.1,
   "User_Count": 124,
   "Developer": "EA Sports",
   "Rating": "E"
 },
 {
   "Name": "Wolfenstein: The Old Blood",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Bethesda Softworks",
   "NA_Sales": 0.07,
   "EU_Sales": 0.07,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.15,
   "Critic_Score": 75,
   "Critic_Count": 23,
   "User_Score": 8,
   "User_Count": 101,
   "Developer": "MachineGames",
   "Rating": ""
 },
 {
   "Name": "Tom Clancy's Rainbow Six: Siege",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Shooter",
   "Publisher": "Ubisoft",
   "NA_Sales": 0.77,
   "EU_Sales": 0.45,
   "JP_Sales": 0,
   "Other_Sales": 0.12,
   "Global_Sales": 1.34,
   "Critic_Score": 74,
   "Critic_Count": 24,
   "User_Score": 6.9,
   "User_Count": 252,
   "Developer": "Ubisoft Montreal",
   "Rating": "M"
 },
 {
   "Name": "Just Cause 3",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Square Enix",
   "NA_Sales": 0.44,
   "EU_Sales": 0.39,
   "JP_Sales": 0,
   "Other_Sales": 0.08,
   "Global_Sales": 0.9,
   "Critic_Score": 71,
   "Critic_Count": 24,
   "User_Score": 7,
   "User_Count": 186,
   "Developer": "Avalanche Studios",
   "Rating": "M"
 },
 {
   "Name": "Stranger of Sword City",
   "Platform": "PSV",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Nippon Ichi Software",
   "NA_Sales": 0.02,
   "EU_Sales": 0,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.04,
   "Critic_Score": 71,
   "Critic_Count": 24,
   "User_Score": 8,
   "User_Count": 30,
   "Developer": "Experience Inc.",
   "Rating": "T"
 },
 {
   "Name": "Shovel Knight",
   "Platform": "WiiU",
   "Year_of_Release": 2015,
   "Genre": "Platform",
   "Publisher": "Yacht Club Games",
   "NA_Sales": 0.05,
   "EU_Sales": 0.04,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.1,
   "Critic_Score": 88,
   "Critic_Count": 24,
   "User_Score": 8.3,
   "User_Count": 280,
   "Developer": "Yacht Club Games",
   "Rating": "E"
 },
 {
   "Name": "Mobile Suit Gundam: Extreme VS Force",
   "Platform": "PSV",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.17,
   "Other_Sales": 0,
   "Global_Sales": 0.17,
   "Critic_Score": 57,
   "Critic_Count": 25,
   "User_Score": 7.3,
   "User_Count": 15,
   "Developer": "Bandai Namco Games",
   "Rating": "E10+"
 },
 {
   "Name": "Assassin's Creed: Rogue",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Ubisoft",
   "NA_Sales": 0.05,
   "EU_Sales": 0.02,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.08,
   "Critic_Score": 74,
   "Critic_Count": 25,
   "User_Score": 7.5,
   "User_Count": 362,
   "Developer": "Ubisoft",
   "Rating": "M"
 },
 {
   "Name": "Transformers: Devastation",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Activision",
   "NA_Sales": 0.09,
   "EU_Sales": 0.04,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.14,
   "Critic_Score": 75,
   "Critic_Count": 25,
   "User_Score": 7.9,
   "User_Count": 55,
   "Developer": "PlatinumGames",
   "Rating": "T"
 },
 {
   "Name": "Senran Kagura: Estival Versus",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Marvelous Interactive",
   "NA_Sales": 0.08,
   "EU_Sales": 0,
   "JP_Sales": 0.08,
   "Other_Sales": 0.02,
   "Global_Sales": 0.18,
   "Critic_Score": 67,
   "Critic_Count": 25,
   "User_Score": 8,
   "User_Count": 96,
   "Developer": "Marvelous Inc.",
   "Rating": "M"
 },
 {
   "Name": "Rory McIlroy PGA Tour",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Electronic Arts",
   "NA_Sales": 0.16,
   "EU_Sales": 0.09,
   "JP_Sales": 0,
   "Other_Sales": 0.02,
   "Global_Sales": 0.27,
   "Critic_Score": 60,
   "Critic_Count": 26,
   "User_Score": 4.3,
   "User_Count": 77,
   "Developer": "EA Tiburon",
   "Rating": "E"
 },
 {
   "Name": "Zombie Army Trilogy",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Shooter",
   "Publisher": "Rebellion Developments",
   "NA_Sales": 0.05,
   "EU_Sales": 0.12,
   "JP_Sales": 0,
   "Other_Sales": 0.03,
   "Global_Sales": 0.2,
   "Critic_Score": 62,
   "Critic_Count": 26,
   "User_Score": 6.8,
   "User_Count": 88,
   "Developer": "Rebellion",
   "Rating": ""
 },
 {
   "Name": "Samurai Warriors 4-II",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Tecmo Koei",
   "NA_Sales": 0.03,
   "EU_Sales": 0.02,
   "JP_Sales": 0.06,
   "Other_Sales": 0.01,
   "Global_Sales": 0.12,
   "Critic_Score": 73,
   "Critic_Count": 26,
   "User_Score": 7.3,
   "User_Count": 24,
   "Developer": "Omega Force",
   "Rating": "T"
 },
 {
   "Name": "Mario vs. Donkey Kong: Tipping Stars",
   "Platform": "WiiU",
   "Year_of_Release": 2015,
   "Genre": "Puzzle",
   "Publisher": "Nintendo",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.01,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": 70,
   "Critic_Count": 26,
   "User_Score": 7.4,
   "User_Count": 72,
   "Developer": "Nintendo, Nintendo Software Technology",
   "Rating": "E"
 },
 {
   "Name": "Dying Light",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Warner Bros. Interactive Entertainment",
   "NA_Sales": 0.86,
   "EU_Sales": 0.3,
   "JP_Sales": 0.01,
   "Other_Sales": 0.12,
   "Global_Sales": 1.29,
   "Critic_Score": 74,
   "Critic_Count": 26,
   "User_Score": 7.8,
   "User_Count": 387,
   "Developer": "Techland",
   "Rating": "M"
 },
 {
   "Name": "7th Dragon III Code: VFD",
   "Platform": "3DS",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Sega",
   "NA_Sales": 0.04,
   "EU_Sales": 0,
   "JP_Sales": 0.12,
   "Other_Sales": 0,
   "Global_Sales": 0.17,
   "Critic_Score": 77,
   "Critic_Count": 26,
   "User_Score": 8.2,
   "User_Count": 38,
   "Developer": "Sega",
   "Rating": "T"
 },
 {
   "Name": "Battlefield: Hardline",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Shooter",
   "Publisher": "Electronic Arts",
   "NA_Sales": 0.72,
   "EU_Sales": 0.37,
   "JP_Sales": 0.01,
   "Other_Sales": 0.11,
   "Global_Sales": 1.21,
   "Critic_Score": 71,
   "Critic_Count": 27,
   "User_Score": 5.1,
   "User_Count": 299,
   "Developer": "Visceral Games",
   "Rating": "M"
 },
 {
   "Name": "NBA Live 16",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Electronic Arts",
   "NA_Sales": 0.1,
   "EU_Sales": 0.04,
   "JP_Sales": 0,
   "Other_Sales": 0.03,
   "Global_Sales": 0.18,
   "Critic_Score": 59,
   "Critic_Count": 27,
   "User_Score": 6.1,
   "User_Count": 70,
   "Developer": "EA Sports",
   "Rating": "E"
 },
 {
   "Name": "Rock Band 4",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Misc",
   "Publisher": "Harmonix Music Systems",
   "NA_Sales": 0.38,
   "EU_Sales": 0.04,
   "JP_Sales": 0,
   "Other_Sales": 0.05,
   "Global_Sales": 0.47,
   "Critic_Score": 79,
   "Critic_Count": 27,
   "User_Score": 6.4,
   "User_Count": 54,
   "Developer": "Harmonix Music Systems",
   "Rating": "T"
 },
 {
   "Name": "NHL 16",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Electronic Arts",
   "NA_Sales": 0.36,
   "EU_Sales": 0.16,
   "JP_Sales": 0,
   "Other_Sales": 0.11,
   "Global_Sales": 0.63,
   "Critic_Score": 78,
   "Critic_Count": 28,
   "User_Score": 5.5,
   "User_Count": 157,
   "Developer": "EA Sports, EA Canada",
   "Rating": "E10+"
 },
 {
   "Name": "Ultra Street Fighter IV",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Fighting",
   "Publisher": "Capcom",
   "NA_Sales": 0,
   "EU_Sales": 0.08,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.1,
   "Critic_Score": 71,
   "Critic_Count": 28,
   "User_Score": 5.9,
   "User_Count": 94,
   "Developer": "Other Ocean Interactive",
   "Rating": "T"
 },
 {
   "Name": "Return to PopoloCrois: A Story of Seasons Fairytale",
   "Platform": "3DS",
   "Year_of_Release": 2015,
   "Genre": "Simulation",
   "Publisher": "Marvelous Entertainment",
   "NA_Sales": 0.05,
   "EU_Sales": 0,
   "JP_Sales": 0.1,
   "Other_Sales": 0.01,
   "Global_Sales": 0.16,
   "Critic_Score": 72,
   "Critic_Count": 28,
   "User_Score": 6.8,
   "User_Count": 15,
   "Developer": "Marvelous Inc.",
   "Rating": "E10+"
 },
 {
   "Name": "Samurai Warriors 4: Empires",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Tecmo Koei",
   "NA_Sales": 0.02,
   "EU_Sales": 0.01,
   "JP_Sales": 0.06,
   "Other_Sales": 0.01,
   "Global_Sales": 0.1,
   "Critic_Score": 71,
   "Critic_Count": 29,
   "User_Score": 6.5,
   "User_Count": 15,
   "Developer": "Omega Force",
   "Rating": "T"
 },
 {
   "Name": "Ride",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Racing",
   "Publisher": "Milestone S.r.l.",
   "NA_Sales": 0.04,
   "EU_Sales": 0.13,
   "JP_Sales": 0.03,
   "Other_Sales": 0.03,
   "Global_Sales": 0.22,
   "Critic_Score": 66,
   "Critic_Count": 30,
   "User_Score": 7,
   "User_Count": 47,
   "Developer": "Milestone S.r.l",
   "Rating": "E"
 },
 {
   "Name": "Wolfenstein: The Old Blood",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Bethesda Softworks",
   "NA_Sales": 0,
   "EU_Sales": 0.08,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.09,
   "Critic_Score": 76,
   "Critic_Count": 30,
   "User_Score": 7.6,
   "User_Count": 338,
   "Developer": "MachineGames",
   "Rating": "M"
 },
 {
   "Name": "Resident Evil: Revelations 2",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Capcom",
   "NA_Sales": 0.13,
   "EU_Sales": 0.24,
   "JP_Sales": 0.1,
   "Other_Sales": 0.07,
   "Global_Sales": 0.55,
   "Critic_Score": 75,
   "Critic_Count": 30,
   "User_Score": 7.7,
   "User_Count": 284,
   "Developer": "Capcom",
   "Rating": "M"
 },
 {
   "Name": "Saint Seiya: Soldiers' Soul",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Fighting",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0,
   "EU_Sales": 0.12,
   "JP_Sales": 0.04,
   "Other_Sales": 0.02,
   "Global_Sales": 0.18,
   "Critic_Score": 59,
   "Critic_Count": 30,
   "User_Score": 7.8,
   "User_Count": 45,
   "Developer": "Dimps Corporation",
   "Rating": "T"
 },
 {
   "Name": "Battlefield: Hardline",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Shooter",
   "Publisher": "Electronic Arts",
   "NA_Sales": 0,
   "EU_Sales": 0.13,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.14,
   "Critic_Score": 71,
   "Critic_Count": 31,
   "User_Score": 3.8,
   "User_Count": 773,
   "Developer": "Visceral Games",
   "Rating": "M"
 },
 {
   "Name": "Evolve",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Shooter",
   "Publisher": "Take-Two Interactive",
   "NA_Sales": 0.37,
   "EU_Sales": 0.2,
   "JP_Sales": 0,
   "Other_Sales": 0.06,
   "Global_Sales": 0.64,
   "Critic_Score": 74,
   "Critic_Count": 31,
   "User_Score": 5.1,
   "User_Count": 336,
   "Developer": "Turtle Rock Studios",
   "Rating": "M"
 },
 {
   "Name": "Rodea the Sky Soldier",
   "Platform": "WiiU",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Nippon Ichi Software",
   "NA_Sales": 0.08,
   "EU_Sales": 0.02,
   "JP_Sales": 0.01,
   "Other_Sales": 0.01,
   "Global_Sales": 0.12,
   "Critic_Score": 45,
   "Critic_Count": 31,
   "User_Score": 6.5,
   "User_Count": 81,
   "Developer": "Prope, Kadokawa",
   "Rating": "E10+"
 },
 {
   "Name": "The Legend of Legacy",
   "Platform": "3DS",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "FuRyu",
   "NA_Sales": 0.12,
   "EU_Sales": 0.01,
   "JP_Sales": 0.1,
   "Other_Sales": 0.02,
   "Global_Sales": 0.25,
   "Critic_Score": 67,
   "Critic_Count": 31,
   "User_Score": 7.1,
   "User_Count": 54,
   "Developer": "FuRyu",
   "Rating": "E10+"
 },
 {
   "Name": "The Talos Principle",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Puzzle",
   "Publisher": "Devolver Digital",
   "NA_Sales": 0,
   "EU_Sales": 0.02,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.03,
   "Critic_Score": 88,
   "Critic_Count": 31,
   "User_Score": 8.4,
   "User_Count": 124,
   "Developer": "Croteam",
   "Rating": "E10+"
 },
 {
   "Name": "Sword Art Online: Lost Song",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0.1,
   "EU_Sales": 0.11,
   "JP_Sales": 0,
   "Other_Sales": 0.04,
   "Global_Sales": 0.25,
   "Critic_Score": 63,
   "Critic_Count": 32,
   "User_Score": 6.3,
   "User_Count": 60,
   "Developer": "Bandai Namco Games, Artdink",
   "Rating": "T"
 },
 {
   "Name": "Dragon Ball Z: Extreme Butoden",
   "Platform": "3DS",
   "Year_of_Release": 2015,
   "Genre": "Fighting",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0.12,
   "EU_Sales": 0.03,
   "JP_Sales": 0.16,
   "Other_Sales": 0.02,
   "Global_Sales": 0.33,
   "Critic_Score": 61,
   "Critic_Count": 32,
   "User_Score": 6.6,
   "User_Count": 32,
   "Developer": "Arc System Works",
   "Rating": "T"
 },
 {
   "Name": "Atelier Sophie: The Alchemist of the Mysterious Book",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Tecmo Koei",
   "NA_Sales": 0.03,
   "EU_Sales": 0.02,
   "JP_Sales": 0.06,
   "Other_Sales": 0.01,
   "Global_Sales": 0.12,
   "Critic_Score": 75,
   "Critic_Count": 32,
   "User_Score": 8.1,
   "User_Count": 47,
   "Developer": "Gust",
   "Rating": ""
 },
 {
   "Name": "Hatsune Miku: Project Mirai DX",
   "Platform": "3DS",
   "Year_of_Release": 2015,
   "Genre": "Misc",
   "Publisher": "Sega",
   "NA_Sales": 0.16,
   "EU_Sales": 0.04,
   "JP_Sales": 0.1,
   "Other_Sales": 0.02,
   "Global_Sales": 0.32,
   "Critic_Score": 80,
   "Critic_Count": 32,
   "User_Score": 8.5,
   "User_Count": 71,
   "Developer": "Sega",
   "Rating": "E10+"
 },
 {
   "Name": "Stella Glow",
   "Platform": "3DS",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Atlus",
   "NA_Sales": 0.16,
   "EU_Sales": 0.01,
   "JP_Sales": 0.05,
   "Other_Sales": 0.02,
   "Global_Sales": 0.24,
   "Critic_Score": 79,
   "Critic_Count": 32,
   "User_Score": 8.7,
   "User_Count": 82,
   "Developer": "Image Epoch, Imageepoch",
   "Rating": "T"
 },
 {
   "Name": "The Witcher 3: Wild Hunt",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0.21,
   "EU_Sales": 0.46,
   "JP_Sales": 0,
   "Other_Sales": 0.05,
   "Global_Sales": 0.72,
   "Critic_Score": 93,
   "Critic_Count": 32,
   "User_Score": 9.3,
   "User_Count": 10665,
   "Developer": "CD Projekt Red Studio",
   "Rating": "M"
 },
 {
   "Name": "Rory McIlroy PGA Tour",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Electronic Arts",
   "NA_Sales": 0.18,
   "EU_Sales": 0.25,
   "JP_Sales": 0,
   "Other_Sales": 0.08,
   "Global_Sales": 0.52,
   "Critic_Score": 61,
   "Critic_Count": 33,
   "User_Score": 3.7,
   "User_Count": 78,
   "Developer": "EA Tiburon",
   "Rating": "E"
 },
 {
   "Name": "Bladestorm: Nightmare",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Tecmo Koei",
   "NA_Sales": 0.08,
   "EU_Sales": 0.04,
   "JP_Sales": 0.03,
   "Other_Sales": 0.02,
   "Global_Sales": 0.17,
   "Critic_Score": 58,
   "Critic_Count": 33,
   "User_Score": 6.5,
   "User_Count": 21,
   "Developer": "Omega Force",
   "Rating": "T"
 },
 {
   "Name": "Nitroplus Blasterz: Heroines Infinite Duel",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Fighting",
   "Publisher": "Marvelous Interactive",
   "NA_Sales": 0.01,
   "EU_Sales": 0,
   "JP_Sales": 0.02,
   "Other_Sales": 0,
   "Global_Sales": 0.04,
   "Critic_Score": 70,
   "Critic_Count": 33,
   "User_Score": 6.9,
   "User_Count": 28,
   "Developer": "Examu, Marvelous Inc.",
   "Rating": "T"
 },
 {
   "Name": "Grand Kingdom",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Nippon Ichi Software",
   "NA_Sales": 0.03,
   "EU_Sales": 0,
   "JP_Sales": 0.03,
   "Other_Sales": 0.01,
   "Global_Sales": 0.07,
   "Critic_Score": 78,
   "Critic_Count": 33,
   "User_Score": 8.1,
   "User_Count": 63,
   "Developer": "Spike Chunsoft",
   "Rating": "T"
 },
 {
   "Name": "Football Manager 2016",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Simulation",
   "Publisher": "Sega",
   "NA_Sales": 0,
   "EU_Sales": 0.33,
   "JP_Sales": 0,
   "Other_Sales": 0.02,
   "Global_Sales": 0.35,
   "Critic_Score": 81,
   "Critic_Count": 34,
   "User_Score": 6.9,
   "User_Count": 97,
   "Developer": "Sega",
   "Rating": "E"
 },
 {
   "Name": "One Piece: Pirate Warriors 3",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0.09,
   "EU_Sales": 0.22,
   "JP_Sales": 0.1,
   "Other_Sales": 0.06,
   "Global_Sales": 0.46,
   "Critic_Score": 74,
   "Critic_Count": 34,
   "User_Score": 7.4,
   "User_Count": 118,
   "Developer": "Omega Force",
   "Rating": "T"
 },
 {
   "Name": "JoJo's Bizarre Adventure: Eyes of Heaven",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Fighting",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0,
   "EU_Sales": 0,
   "JP_Sales": 0.03,
   "Other_Sales": 0,
   "Global_Sales": 0.03,
   "Critic_Score": 61,
   "Critic_Count": 35,
   "User_Score": 7.4,
   "User_Count": 44,
   "Developer": "CyberConnect2",
   "Rating": "T"
 },
 {
   "Name": "Toukiden Kiwami",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Tecmo Koei",
   "NA_Sales": 0.05,
   "EU_Sales": 0.07,
   "JP_Sales": 0.02,
   "Other_Sales": 0.02,
   "Global_Sales": 0.17,
   "Critic_Score": 74,
   "Critic_Count": 35,
   "User_Score": 7.6,
   "User_Count": 74,
   "Developer": "Koei Tecmo Games",
   "Rating": "T"
 },
 {
   "Name": "God Eater 2: Rage Burst",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0.09,
   "Other_Sales": 0,
   "Global_Sales": 0.11,
   "Critic_Score": 69,
   "Critic_Count": 35,
   "User_Score": 8,
   "User_Count": 79,
   "Developer": "Shift",
   "Rating": "T"
 },
 {
   "Name": "Madden NFL 16",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Electronic Arts",
   "NA_Sales": 2.34,
   "EU_Sales": 0.3,
   "JP_Sales": 0,
   "Other_Sales": 0.6,
   "Global_Sales": 3.24,
   "Critic_Score": 83,
   "Critic_Count": 37,
   "User_Score": 5.9,
   "User_Count": 180,
   "Developer": "EA Sports",
   "Rating": "E"
 },
 {
   "Name": "Project CARS",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Racing",
   "Publisher": "Slightly Mad Studios",
   "NA_Sales": 0.2,
   "EU_Sales": 0.7,
   "JP_Sales": 0.02,
   "Other_Sales": 0.16,
   "Global_Sales": 1.09,
   "Critic_Score": 83,
   "Critic_Count": 37,
   "User_Score": 6.6,
   "User_Count": 363,
   "Developer": "Slightly Mad Studios",
   "Rating": "E"
 },
 {
   "Name": "Tom Clancy's Rainbow Six: Siege",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Shooter",
   "Publisher": "Ubisoft",
   "NA_Sales": 0.13,
   "EU_Sales": 0.08,
   "JP_Sales": 0,
   "Other_Sales": 0.02,
   "Global_Sales": 0.23,
   "Critic_Score": 79,
   "Critic_Count": 37,
   "User_Score": 6.9,
   "User_Count": 734,
   "Developer": "Ubisoft Montreal",
   "Rating": "M"
 },
 {
   "Name": "Act of Aggression",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Strategy",
   "Publisher": "Focus Home Interactive",
   "NA_Sales": 0,
   "EU_Sales": 0.01,
   "JP_Sales": 0,
   "Other_Sales": 0,
   "Global_Sales": 0.01,
   "Critic_Score": 71,
   "Critic_Count": 37,
   "User_Score": 7.1,
   "User_Count": 93,
   "Developer": "Eugen Systems",
   "Rating": ""
 },
 {
   "Name": "Fallout 4",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Bethesda Softworks",
   "NA_Sales": 0.51,
   "EU_Sales": 0.67,
   "JP_Sales": 0,
   "Other_Sales": 0.1,
   "Global_Sales": 1.29,
   "Critic_Score": 84,
   "Critic_Count": 38,
   "User_Score": 5.4,
   "User_Count": 7512,
   "Developer": "Bethesda Game Studios",
   "Rating": "M"
 },
 {
   "Name": "Evolve",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Shooter",
   "Publisher": "Take-Two Interactive",
   "NA_Sales": 0.08,
   "EU_Sales": 0.1,
   "JP_Sales": 0,
   "Other_Sales": 0.02,
   "Global_Sales": 0.19,
   "Critic_Score": 77,
   "Critic_Count": 39,
   "User_Score": 4.3,
   "User_Count": 969,
   "Developer": "Turtle Rock Studios",
   "Rating": "M"
 },
 {
   "Name": "Fallout 4",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Bethesda Softworks",
   "NA_Sales": 2.51,
   "EU_Sales": 1.32,
   "JP_Sales": 0.01,
   "Other_Sales": 0.38,
   "Global_Sales": 4.22,
   "Critic_Score": 88,
   "Critic_Count": 39,
   "User_Score": 6.2,
   "User_Count": 1749,
   "Developer": "Bethesda Game Studios",
   "Rating": "M"
 },
 {
   "Name": "Tom Clancy's Rainbow Six: Siege",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Shooter",
   "Publisher": "Ubisoft",
   "NA_Sales": 0.55,
   "EU_Sales": 1.19,
   "JP_Sales": 0.14,
   "Other_Sales": 0.33,
   "Global_Sales": 2.21,
   "Critic_Score": 73,
   "Critic_Count": 40,
   "User_Score": 7.3,
   "User_Count": 480,
   "Developer": "Ubisoft Montreal",
   "Rating": "M"
 },
 {
   "Name": "Nights of Azure",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Tecmo Koei",
   "NA_Sales": 0.03,
   "EU_Sales": 0.02,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.06,
   "Critic_Score": 67,
   "Critic_Count": 40,
   "User_Score": 7.6,
   "User_Count": 71,
   "Developer": "Gust",
   "Rating": "T"
 },
 {
   "Name": "Dying Light",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Warner Bros. Interactive Entertainment",
   "NA_Sales": 0.12,
   "EU_Sales": 0.06,
   "JP_Sales": 0,
   "Other_Sales": 0.02,
   "Global_Sales": 0.2,
   "Critic_Score": 75,
   "Critic_Count": 40,
   "User_Score": 7.9,
   "User_Count": 1295,
   "Developer": "Techland",
   "Rating": "M"
 },
 {
   "Name": "Earth Defense Force 4.1: The Shadow of New Despair",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Shooter",
   "Publisher": "Xseed Games",
   "NA_Sales": 0.03,
   "EU_Sales": 0.02,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.06,
   "Critic_Score": 64,
   "Critic_Count": 40,
   "User_Score": 7.9,
   "User_Count": 51,
   "Developer": "Sandlot",
   "Rating": "M"
 },
 {
   "Name": "FIFA 16",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Electronic Arts",
   "NA_Sales": 1.12,
   "EU_Sales": 6.12,
   "JP_Sales": 0.06,
   "Other_Sales": 1.28,
   "Global_Sales": 8.57,
   "Critic_Score": 82,
   "Critic_Count": 42,
   "User_Score": 4.3,
   "User_Count": 896,
   "Developer": "EA Sports",
   "Rating": "E"
 },
 {
   "Name": "Just Cause 3",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Square Enix",
   "NA_Sales": 0.47,
   "EU_Sales": 1.03,
   "JP_Sales": 0.07,
   "Other_Sales": 0.28,
   "Global_Sales": 1.86,
   "Critic_Score": 73,
   "Critic_Count": 42,
   "User_Score": 6.5,
   "User_Count": 403,
   "Developer": "Avalanche Studios",
   "Rating": "M"
 },
 {
   "Name": "Tony Hawk's Pro Skater 5",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Activision",
   "NA_Sales": 0.09,
   "EU_Sales": 0.08,
   "JP_Sales": 0,
   "Other_Sales": 0.03,
   "Global_Sales": 0.21,
   "Critic_Score": 32,
   "Critic_Count": 43,
   "User_Score": 1.5,
   "User_Count": 427,
   "Developer": "Robomodo",
   "Rating": "T"
 },
 {
   "Name": "Arslan: The Warriors of Legend",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Tecmo Koei",
   "NA_Sales": 0.03,
   "EU_Sales": 0.01,
   "JP_Sales": 0.04,
   "Other_Sales": 0.01,
   "Global_Sales": 0.09,
   "Critic_Score": 69,
   "Critic_Count": 43,
   "User_Score": 6.6,
   "User_Count": 23,
   "Developer": "Omega Force",
   "Rating": "T"
 },
 {
   "Name": "Disgaea 5: Alliance of Vengeance",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Nippon Ichi Software",
   "NA_Sales": 0.11,
   "EU_Sales": 0.08,
   "JP_Sales": 0.06,
   "Other_Sales": 0.04,
   "Global_Sales": 0.29,
   "Critic_Score": 80,
   "Critic_Count": 43,
   "User_Score": 8.1,
   "User_Count": 173,
   "Developer": "Nippon Ichi Software",
   "Rating": "T"
 },
 {
   "Name": "Assassin's Creed Chronicles: China",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Ubisoft",
   "NA_Sales": 0,
   "EU_Sales": 0.03,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.04,
   "Critic_Score": 69,
   "Critic_Count": 44,
   "User_Score": 6.4,
   "User_Count": 83,
   "Developer": "Climax Group, Climax Studios",
   "Rating": "T"
 },
 {
   "Name": "MLB 15: The Show",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Sony Computer Entertainment",
   "NA_Sales": 0.68,
   "EU_Sales": 0.08,
   "JP_Sales": 0,
   "Other_Sales": 0.17,
   "Global_Sales": 0.92,
   "Critic_Score": 80,
   "Critic_Count": 44,
   "User_Score": 7.8,
   "User_Count": 190,
   "Developer": "SCEA San Diego Studios",
   "Rating": "E"
 },
 {
   "Name": "Etrian Mystery Dungeon",
   "Platform": "3DS",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Nippon Ichi Software",
   "NA_Sales": 0.09,
   "EU_Sales": 0.01,
   "JP_Sales": 0.13,
   "Other_Sales": 0.01,
   "Global_Sales": 0.24,
   "Critic_Score": 77,
   "Critic_Count": 44,
   "User_Score": 7.9,
   "User_Count": 49,
   "Developer": "Spike Chunsoft",
   "Rating": "E10+"
 },
 {
   "Name": "Pokemon Super Mystery Dungeon",
   "Platform": "3DS",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Nintendo",
   "NA_Sales": 0.48,
   "EU_Sales": 0.35,
   "JP_Sales": 0.34,
   "Other_Sales": 0.08,
   "Global_Sales": 1.25,
   "Critic_Score": 69,
   "Critic_Count": 44,
   "User_Score": 8.8,
   "User_Count": 190,
   "Developer": "Spike Chunsoft Co. Ltd., Spike Chunsoft",
   "Rating": "E"
 },
 {
   "Name": "FIFA 16",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Electronic Arts",
   "NA_Sales": 0.89,
   "EU_Sales": 2.12,
   "JP_Sales": 0,
   "Other_Sales": 0.24,
   "Global_Sales": 3.25,
   "Critic_Score": 84,
   "Critic_Count": 45,
   "User_Score": 4.4,
   "User_Count": 459,
   "Developer": "EA Sports",
   "Rating": "E"
 },
 {
   "Name": "Saints Row: Gat out of Hell",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Deep Silver",
   "NA_Sales": 0,
   "EU_Sales": 0.04,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.05,
   "Critic_Score": 64,
   "Critic_Count": 45,
   "User_Score": 5.7,
   "User_Count": 98,
   "Developer": "Volition Inc.",
   "Rating": "M"
 },
 {
   "Name": "Anno 2205",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Strategy",
   "Publisher": "Ubisoft",
   "NA_Sales": 0.02,
   "EU_Sales": 0.22,
   "JP_Sales": 0,
   "Other_Sales": 0.02,
   "Global_Sales": 0.25,
   "Critic_Score": 72,
   "Critic_Count": 45,
   "User_Score": 5.9,
   "User_Count": 278,
   "Developer": "Blue Byte",
   "Rating": "E10+"
 },
 {
   "Name": "Evolve",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Shooter",
   "Publisher": "Take-Two Interactive",
   "NA_Sales": 0.36,
   "EU_Sales": 0.41,
   "JP_Sales": 0.05,
   "Other_Sales": 0.15,
   "Global_Sales": 0.96,
   "Critic_Score": 76,
   "Critic_Count": 46,
   "User_Score": 4.3,
   "User_Count": 894,
   "Developer": "Turtle Rock Studios",
   "Rating": "M"
 },
 {
   "Name": "Battlefield: Hardline",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Shooter",
   "Publisher": "Electronic Arts",
   "NA_Sales": 0.71,
   "EU_Sales": 0.94,
   "JP_Sales": 0.14,
   "Other_Sales": 0.32,
   "Global_Sales": 2.1,
   "Critic_Score": 73,
   "Critic_Count": 46,
   "User_Score": 5,
   "User_Count": 845,
   "Developer": "Visceral Games",
   "Rating": "M"
 },
 {
   "Name": "F1 2015",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Racing",
   "Publisher": "Codemasters",
   "NA_Sales": 0.09,
   "EU_Sales": 0.45,
   "JP_Sales": 0.03,
   "Other_Sales": 0.1,
   "Global_Sales": 0.66,
   "Critic_Score": 65,
   "Critic_Count": 46,
   "User_Score": 6.3,
   "User_Count": 43,
   "Developer": "Codemasters",
   "Rating": "E"
 },
 {
   "Name": "LEGO Jurassic World",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Warner Bros. Interactive Entertainment",
   "NA_Sales": 0.32,
   "EU_Sales": 0.42,
   "JP_Sales": 0.02,
   "Other_Sales": 0.14,
   "Global_Sales": 0.9,
   "Critic_Score": 70,
   "Critic_Count": 46,
   "User_Score": 7,
   "User_Count": 80,
   "Developer": "TT Games",
   "Rating": "E10+"
 },
 {
   "Name": "WWE 2K16",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Take-Two Interactive",
   "NA_Sales": 0.41,
   "EU_Sales": 0.6,
   "JP_Sales": 0,
   "Other_Sales": 0.2,
   "Global_Sales": 1.21,
   "Critic_Score": 73,
   "Critic_Count": 47,
   "User_Score": 7.4,
   "User_Count": 237,
   "Developer": "Yuke's",
   "Rating": "T"
 },
 {
   "Name": "Project CARS",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Racing",
   "Publisher": "Slightly Mad Studios",
   "NA_Sales": 0,
   "EU_Sales": 0.12,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.13,
   "Critic_Score": 83,
   "Critic_Count": 48,
   "User_Score": 7.1,
   "User_Count": 418,
   "Developer": "Slightly Mad Studios",
   "Rating": "E"
 },
 {
   "Name": "Borderlands: The Handsome Collection",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Shooter",
   "Publisher": "Take-Two Interactive",
   "NA_Sales": 0.38,
   "EU_Sales": 0.33,
   "JP_Sales": 0.03,
   "Other_Sales": 0.14,
   "Global_Sales": 0.88,
   "Critic_Score": 82,
   "Critic_Count": 49,
   "User_Score": 7.8,
   "User_Count": 345,
   "Developer": "Gearbox Software",
   "Rating": "M"
 },
 {
   "Name": "Just Cause 3",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Square Enix",
   "NA_Sales": 0.03,
   "EU_Sales": 0.11,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.14,
   "Critic_Score": 74,
   "Critic_Count": 50,
   "User_Score": 5.3,
   "User_Count": 529,
   "Developer": "Avalanche Studios",
   "Rating": "M"
 },
 {
   "Name": "Transformers: Devastation",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Activision",
   "NA_Sales": 0.1,
   "EU_Sales": 0.09,
   "JP_Sales": 0,
   "Other_Sales": 0.04,
   "Global_Sales": 0.23,
   "Critic_Score": 77,
   "Critic_Count": 50,
   "User_Score": 7.5,
   "User_Count": 160,
   "Developer": "PlatinumGames",
   "Rating": "T"
 },
 {
   "Name": "Dragon Ball: XenoVerse",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Fighting",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0.3,
   "EU_Sales": 0.52,
   "JP_Sales": 0.12,
   "Other_Sales": 0.16,
   "Global_Sales": 1.11,
   "Critic_Score": 69,
   "Critic_Count": 50,
   "User_Score": 7.7,
   "User_Count": 598,
   "Developer": "Dimps Corporation",
   "Rating": "T"
 },
 {
   "Name": "Skylanders: SuperChargers",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Activision",
   "NA_Sales": 0.17,
   "EU_Sales": 0.08,
   "JP_Sales": 0,
   "Other_Sales": 0.05,
   "Global_Sales": 0.31,
   "Critic_Score": 81,
   "Critic_Count": 51,
   "User_Score": 3.3,
   "User_Count": 29,
   "Developer": "Vicarious Visions",
   "Rating": "E10+"
 },
 {
   "Name": "Rock Band 4",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Misc",
   "Publisher": "Harmonix Music Systems",
   "NA_Sales": 0.26,
   "EU_Sales": 0.05,
   "JP_Sales": 0,
   "Other_Sales": 0.07,
   "Global_Sales": 0.38,
   "Critic_Score": 78,
   "Critic_Count": 51,
   "User_Score": 6.3,
   "User_Count": 87,
   "Developer": "Harmonix Music Systems",
   "Rating": "T"
 },
 {
   "Name": "NBA 2K16",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Take-Two Interactive",
   "NA_Sales": 2.49,
   "EU_Sales": 0.66,
   "JP_Sales": 0.03,
   "Other_Sales": 0.69,
   "Global_Sales": 3.88,
   "Critic_Score": 87,
   "Critic_Count": 51,
   "User_Score": 6.7,
   "User_Count": 364,
   "Developer": "Visual Concepts",
   "Rating": "E10+"
 },
 {
   "Name": "Persona 4: Dancing All Night",
   "Platform": "PSV",
   "Year_of_Release": 2015,
   "Genre": "Misc",
   "Publisher": "Nippon Ichi Software",
   "NA_Sales": 0.09,
   "EU_Sales": 0.04,
   "JP_Sales": 0.15,
   "Other_Sales": 0.04,
   "Global_Sales": 0.32,
   "Critic_Score": 76,
   "Critic_Count": 51,
   "User_Score": 8.6,
   "User_Count": 83,
   "Developer": "Atlus, Dingo Inc.",
   "Rating": "T"
 },
 {
   "Name": "LEGO Dimensions",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Warner Bros. Interactive Entertainment",
   "NA_Sales": 0.24,
   "EU_Sales": 0.37,
   "JP_Sales": 0,
   "Other_Sales": 0.12,
   "Global_Sales": 0.73,
   "Critic_Score": 80,
   "Critic_Count": 53,
   "User_Score": 7.1,
   "User_Count": 65,
   "Developer": "Traveller's Tales",
   "Rating": "E10+"
 },
 {
   "Name": "Devil's Third",
   "Platform": "WiiU",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Nintendo",
   "NA_Sales": 0.04,
   "EU_Sales": 0.02,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.06,
   "Critic_Score": 43,
   "Critic_Count": 54,
   "User_Score": 6.5,
   "User_Count": 283,
   "Developer": "Valhalla Game Studios",
   "Rating": "M"
 },
 {
   "Name": "Pro Evolution Soccer 2016",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Konami Digital Entertainment",
   "NA_Sales": 0.13,
   "EU_Sales": 0.42,
   "JP_Sales": 0.13,
   "Other_Sales": 0.1,
   "Global_Sales": 0.79,
   "Critic_Score": 87,
   "Critic_Count": 54,
   "User_Score": 7.1,
   "User_Count": 680,
   "Developer": "Konami",
   "Rating": "E"
 },
 {
   "Name": "Wolfenstein: The Old Blood",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Bethesda Softworks",
   "NA_Sales": 0.1,
   "EU_Sales": 0.25,
   "JP_Sales": 0.02,
   "Other_Sales": 0.06,
   "Global_Sales": 0.43,
   "Critic_Score": 76,
   "Critic_Count": 54,
   "User_Score": 8,
   "User_Count": 267,
   "Developer": "MachineGames",
   "Rating": ""
 },
 {
   "Name": "Grand Theft Auto V",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Take-Two Interactive",
   "NA_Sales": 0.39,
   "EU_Sales": 0.69,
   "JP_Sales": 0,
   "Other_Sales": 0.09,
   "Global_Sales": 1.17,
   "Critic_Score": 96,
   "Critic_Count": 57,
   "User_Score": 7.9,
   "User_Count": 3756,
   "Developer": "Rockstar North",
   "Rating": "M"
 },
 {
   "Name": "Mario Tennis Ultra Smash",
   "Platform": "WiiU",
   "Year_of_Release": 2015,
   "Genre": "Sports",
   "Publisher": "Nintendo",
   "NA_Sales": 0.13,
   "EU_Sales": 0.15,
   "JP_Sales": 0.14,
   "Other_Sales": 0.02,
   "Global_Sales": 0.44,
   "Critic_Score": 58,
   "Critic_Count": 58,
   "User_Score": 5.3,
   "User_Count": 133,
   "Developer": "Nintendo, Camelot Software Planning",
   "Rating": "E"
 },
 {
   "Name": "Fallout 4",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Bethesda Softworks",
   "NA_Sales": 2.53,
   "EU_Sales": 3.27,
   "JP_Sales": 0.24,
   "Other_Sales": 1.13,
   "Global_Sales": 7.16,
   "Critic_Score": 87,
   "Critic_Count": 58,
   "User_Score": 6.5,
   "User_Count": 4228,
   "Developer": "Bethesda Game Studios",
   "Rating": "M"
 },
 {
   "Name": "Dying Light",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Warner Bros. Interactive Entertainment",
   "NA_Sales": 0.96,
   "EU_Sales": 0.67,
   "JP_Sales": 0.12,
   "Other_Sales": 0.34,
   "Global_Sales": 2.09,
   "Critic_Score": 74,
   "Critic_Count": 58,
   "User_Score": 7.9,
   "User_Count": 1287,
   "Developer": "Techland",
   "Rating": "M"
 },
 {
   "Name": "Tales of Zestiria",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 0.17,
   "EU_Sales": 0.15,
   "JP_Sales": 0.02,
   "Other_Sales": 0.06,
   "Global_Sales": 0.4,
   "Critic_Score": 72,
   "Critic_Count": 59,
   "User_Score": 6.8,
   "User_Count": 315,
   "Developer": "Bandai Namco Games",
   "Rating": "T"
 },
 {
   "Name": "Animal Crossing: Happy Home Designer",
   "Platform": "3DS",
   "Year_of_Release": 2015,
   "Genre": "Simulation",
   "Publisher": "Nintendo",
   "NA_Sales": 0.51,
   "EU_Sales": 1.02,
   "JP_Sales": 1.4,
   "Other_Sales": 0.12,
   "Global_Sales": 3.05,
   "Critic_Score": 66,
   "Critic_Count": 60,
   "User_Score": 6.9,
   "User_Count": 106,
   "Developer": "Nintendo",
   "Rating": "E"
 },
 {
   "Name": "Cities: Skylines",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Simulation",
   "Publisher": "Paradox Interactive",
   "NA_Sales": 0,
   "EU_Sales": 0.13,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.14,
   "Critic_Score": 85,
   "Critic_Count": 60,
   "User_Score": 8.9,
   "User_Count": 1404,
   "Developer": "Colossal Order",
   "Rating": "E"
 },
 {
   "Name": "Gravity Rush Remastered",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Sony Computer Entertainment",
   "NA_Sales": 0.02,
   "EU_Sales": 0.05,
   "JP_Sales": 0.04,
   "Other_Sales": 0.01,
   "Global_Sales": 0.13,
   "Critic_Score": 80,
   "Critic_Count": 62,
   "User_Score": 8.2,
   "User_Count": 153,
   "Developer": "Bluepoint Games",
   "Rating": "T"
 },
 {
   "Name": "StarCraft II: Legacy of the Void",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Strategy",
   "Publisher": "Activision",
   "NA_Sales": 0.19,
   "EU_Sales": 0.29,
   "JP_Sales": 0,
   "Other_Sales": 0.04,
   "Global_Sales": 0.53,
   "Critic_Score": 88,
   "Critic_Count": 62,
   "User_Score": 8.3,
   "User_Count": 833,
   "Developer": "Blizzard Entertainment",
   "Rating": "T"
 },
 {
   "Name": "Wasteland 2",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "inXile Entertainment",
   "NA_Sales": 0.03,
   "EU_Sales": 0.06,
   "JP_Sales": 0,
   "Other_Sales": 0.01,
   "Global_Sales": 0.1,
   "Critic_Score": 81,
   "Critic_Count": 65,
   "User_Score": 7.3,
   "User_Count": 1170,
   "Developer": "InXile Entertainment",
   "Rating": "M"
 },
 {
   "Name": "Mario Party 10",
   "Platform": "WiiU",
   "Year_of_Release": 2015,
   "Genre": "Misc",
   "Publisher": "Nintendo",
   "NA_Sales": 0.69,
   "EU_Sales": 0.53,
   "JP_Sales": 0.24,
   "Other_Sales": 0.12,
   "Global_Sales": 1.58,
   "Critic_Score": 66,
   "Critic_Count": 66,
   "User_Score": 6.5,
   "User_Count": 279,
   "Developer": "Nintendo, Nd Cube",
   "Rating": "E"
 },
 {
   "Name": "Total War: Attila",
   "Platform": "PC",
   "Year_of_Release": 2015,
   "Genre": "Strategy",
   "Publisher": "Sega",
   "NA_Sales": 0.09,
   "EU_Sales": 0.13,
   "JP_Sales": 0,
   "Other_Sales": 0.02,
   "Global_Sales": 0.24,
   "Critic_Score": 80,
   "Critic_Count": 66,
   "User_Score": 7.3,
   "User_Count": 520,
   "Developer": "Creative Assembly",
   "Rating": "T"
 },
 {
   "Name": "Guitar Hero Live",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Misc",
   "Publisher": "Activision",
   "NA_Sales": 0.34,
   "EU_Sales": 0.38,
   "JP_Sales": 0,
   "Other_Sales": 0.14,
   "Global_Sales": 0.86,
   "Critic_Score": 80,
   "Critic_Count": 69,
   "User_Score": 6.2,
   "User_Count": 160,
   "Developer": "FreeStyleGames",
   "Rating": "T"
 },
 {
   "Name": "Code Name: S.T.E.A.M.",
   "Platform": "3DS",
   "Year_of_Release": 2015,
   "Genre": "Strategy",
   "Publisher": "Nintendo",
   "NA_Sales": 0.14,
   "EU_Sales": 0.05,
   "JP_Sales": 0.01,
   "Other_Sales": 0.02,
   "Global_Sales": 0.21,
   "Critic_Score": 69,
   "Critic_Count": 69,
   "User_Score": 7.7,
   "User_Count": 125,
   "Developer": "Intelligent Systems",
   "Rating": "T"
 },
 {
   "Name": "Bravely Second: End Layer",
   "Platform": "3DS",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Nintendo",
   "NA_Sales": 0.17,
   "EU_Sales": 0.1,
   "JP_Sales": 0.18,
   "Other_Sales": 0.03,
   "Global_Sales": 0.49,
   "Critic_Score": 81,
   "Critic_Count": 70,
   "User_Score": 7.4,
   "User_Count": 103,
   "Developer": "Silicon Studio",
   "Rating": "T"
 },
 {
   "Name": "Tearaway Unfolded",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Platform",
   "Publisher": "Sony Computer Entertainment",
   "NA_Sales": 0.09,
   "EU_Sales": 0.13,
   "JP_Sales": 0,
   "Other_Sales": 0.04,
   "Global_Sales": 0.26,
   "Critic_Score": 81,
   "Critic_Count": 70,
   "User_Score": 8.1,
   "User_Count": 188,
   "Developer": "Media Molecule",
   "Rating": "E"
 },
 {
   "Name": "Kirby and the Rainbow Curse",
   "Platform": "WiiU",
   "Year_of_Release": 2015,
   "Genre": "Platform",
   "Publisher": "Nintendo",
   "NA_Sales": 0.22,
   "EU_Sales": 0.13,
   "JP_Sales": 0.12,
   "Other_Sales": 0.04,
   "Global_Sales": 0.52,
   "Critic_Score": 73,
   "Critic_Count": 72,
   "User_Score": 8,
   "User_Count": 227,
   "Developer": "HAL Labs",
   "Rating": "E"
 },
 {
   "Name": "The Legend of Zelda: Tri Force Heroes",
   "Platform": "3DS",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Nintendo",
   "NA_Sales": 0.53,
   "EU_Sales": 0.33,
   "JP_Sales": 0.17,
   "Other_Sales": 0.08,
   "Global_Sales": 1.12,
   "Critic_Score": 73,
   "Critic_Count": 73,
   "User_Score": 7.6,
   "User_Count": 179,
   "Developer": "Nintendo",
   "Rating": "E"
 },
 {
   "Name": "Gears of War: Ultimate Edition",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Shooter",
   "Publisher": "Microsoft Game Studios",
   "NA_Sales": 2.61,
   "EU_Sales": 0.33,
   "JP_Sales": 0,
   "Other_Sales": 0.34,
   "Global_Sales": 3.28,
   "Critic_Score": 82,
   "Critic_Count": 74,
   "User_Score": 7.5,
   "User_Count": 563,
   "Developer": "Splash Damage, The Coalition",
   "Rating": "M"
 },
 {
   "Name": "Rare Replay",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Misc",
   "Publisher": "Microsoft Game Studios",
   "NA_Sales": 0.49,
   "EU_Sales": 0.22,
   "JP_Sales": 0.01,
   "Other_Sales": 0.07,
   "Global_Sales": 0.79,
   "Critic_Score": 84,
   "Critic_Count": 75,
   "User_Score": 7.7,
   "User_Count": 325,
   "Developer": "Rare Ltd.",
   "Rating": "M"
 },
 {
   "Name": "Uncharted: The Nathan Drake Collection",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Sony Computer Entertainment",
   "NA_Sales": 2.07,
   "EU_Sales": 1.71,
   "JP_Sales": 0.08,
   "Other_Sales": 0.76,
   "Global_Sales": 4.62,
   "Critic_Score": 86,
   "Critic_Count": 78,
   "User_Score": 8.1,
   "User_Count": 1264,
   "Developer": "Bluepoint Games",
   "Rating": "T"
 },
 {
   "Name": "The Witcher 3: Wild Hunt",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Namco Bandai Games",
   "NA_Sales": 1.02,
   "EU_Sales": 2.13,
   "JP_Sales": 0.23,
   "Other_Sales": 0.59,
   "Global_Sales": 3.97,
   "Critic_Score": 92,
   "Critic_Count": 79,
   "User_Score": 9.2,
   "User_Count": 10179,
   "Developer": "CD Projekt Red Studio",
   "Rating": "M"
 },
 {
   "Name": "Destiny: The Taken King",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Shooter",
   "Publisher": "Activision",
   "NA_Sales": 0.78,
   "EU_Sales": 0.79,
   "JP_Sales": 0.04,
   "Other_Sales": 0.31,
   "Global_Sales": 1.93,
   "Critic_Score": 86,
   "Critic_Count": 81,
   "User_Score": 6,
   "User_Count": 1079,
   "Developer": "Bungie",
   "Rating": "T"
 },
 {
   "Name": "Mortal Kombat X",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Fighting",
   "Publisher": "Warner Bros. Interactive Entertainment",
   "NA_Sales": 1.5,
   "EU_Sales": 0.8,
   "JP_Sales": 0,
   "Other_Sales": 0.48,
   "Global_Sales": 2.78,
   "Critic_Score": 83,
   "Critic_Count": 81,
   "User_Score": 7.7,
   "User_Count": 836,
   "Developer": "Warner Bros. Interactive Entertainment, NetherRealm Studios",
   "Rating": "M"
 },
 {
   "Name": "The Legend of Zelda: Majora's Mask 3D",
   "Platform": "3DS",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Nintendo",
   "NA_Sales": 1.15,
   "EU_Sales": 0.55,
   "JP_Sales": 0.47,
   "Other_Sales": 0.17,
   "Global_Sales": 2.34,
   "Critic_Score": 89,
   "Critic_Count": 82,
   "User_Score": 9,
   "User_Count": 478,
   "Developer": "GREZZO",
   "Rating": "E10+"
 },
 {
   "Name": "Yoshi's Woolly World",
   "Platform": "WiiU",
   "Year_of_Release": 2015,
   "Genre": "Platform",
   "Publisher": "Nintendo",
   "NA_Sales": 0.62,
   "EU_Sales": 0.47,
   "JP_Sales": 0.11,
   "Other_Sales": 0.1,
   "Global_Sales": 1.3,
   "Critic_Score": 78,
   "Critic_Count": 83,
   "User_Score": 8.5,
   "User_Count": 376,
   "Developer": "Good-Feel",
   "Rating": "E"
 },
 {
   "Name": "Forza Motorsport 6",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Racing",
   "Publisher": "Microsoft Game Studios",
   "NA_Sales": 0.73,
   "EU_Sales": 0.9,
   "JP_Sales": 0.03,
   "Other_Sales": 0.14,
   "Global_Sales": 1.8,
   "Critic_Score": 87,
   "Critic_Count": 85,
   "User_Score": 7.9,
   "User_Count": 863,
   "Developer": "Turn 10",
   "Rating": "E"
 },
 {
   "Name": "Super Mario Maker",
   "Platform": "WiiU",
   "Year_of_Release": 2015,
   "Genre": "Platform",
   "Publisher": "Nintendo",
   "NA_Sales": 1.18,
   "EU_Sales": 0.89,
   "JP_Sales": 0.94,
   "Other_Sales": 0.2,
   "Global_Sales": 3.21,
   "Critic_Score": 88,
   "Critic_Count": 85,
   "User_Score": 8.7,
   "User_Count": 691,
   "Developer": "Nintendo",
   "Rating": "E"
 },
 {
   "Name": "Assassin's Creed Syndicate",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Ubisoft",
   "NA_Sales": 0.81,
   "EU_Sales": 1.99,
   "JP_Sales": 0.07,
   "Other_Sales": 0.52,
   "Global_Sales": 3.39,
   "Critic_Score": 76,
   "Critic_Count": 86,
   "User_Score": 6.8,
   "User_Count": 1319,
   "Developer": "Ubisoft Quebec",
   "Rating": "M"
 },
 {
   "Name": "Metal Gear Solid V: The Phantom Pain",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Konami Digital Entertainment",
   "NA_Sales": 1.09,
   "EU_Sales": 1.36,
   "JP_Sales": 0.49,
   "Other_Sales": 0.48,
   "Global_Sales": 3.41,
   "Critic_Score": 93,
   "Critic_Count": 86,
   "User_Score": 8.2,
   "User_Count": 3943,
   "Developer": "Kojima Productions, Moby Dick Studio",
   "Rating": "M"
 },
 {
   "Name": "Xenoblade Chronicles X",
   "Platform": "WiiU",
   "Year_of_Release": 2015,
   "Genre": "Role-Playing",
   "Publisher": "Nintendo",
   "NA_Sales": 0.36,
   "EU_Sales": 0.28,
   "JP_Sales": 0.14,
   "Other_Sales": 0.06,
   "Global_Sales": 0.84,
   "Critic_Score": 84,
   "Critic_Count": 87,
   "User_Score": 8.9,
   "User_Count": 1548,
   "Developer": "Monolith Soft",
   "Rating": "T"
 },
 {
   "Name": "Splatoon",
   "Platform": "WiiU",
   "Year_of_Release": 2015,
   "Genre": "Shooter",
   "Publisher": "Nintendo",
   "NA_Sales": 1.54,
   "EU_Sales": 1.18,
   "JP_Sales": 1.46,
   "Other_Sales": 0.26,
   "Global_Sales": 4.43,
   "Critic_Score": 81,
   "Critic_Count": 88,
   "User_Score": 8.5,
   "User_Count": 1184,
   "Developer": "Nintendo",
   "Rating": "E10+"
 },
 {
   "Name": "Batman: Arkham Knight",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Warner Bros. Interactive Entertainment",
   "NA_Sales": 1.53,
   "EU_Sales": 1.69,
   "JP_Sales": 0.1,
   "Other_Sales": 0.64,
   "Global_Sales": 3.95,
   "Critic_Score": 87,
   "Critic_Count": 89,
   "User_Score": 7.6,
   "User_Count": 2679,
   "Developer": "Rocksteady Studios",
   "Rating": "M"
 },
 {
   "Name": "The Order: 1886",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Shooter",
   "Publisher": "Sony Computer Entertainment",
   "NA_Sales": 0.61,
   "EU_Sales": 0.78,
   "JP_Sales": 0.06,
   "Other_Sales": 0.27,
   "Global_Sales": 1.74,
   "Critic_Score": 63,
   "Critic_Count": 94,
   "User_Score": 6.6,
   "User_Count": 3172,
   "Developer": "Ready at Dawn, SCE Santa Monica",
   "Rating": "M"
 },
 {
   "Name": "Bloodborne",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Action",
   "Publisher": "Sony Computer Entertainment",
   "NA_Sales": 1.03,
   "EU_Sales": 0.81,
   "JP_Sales": 0.26,
   "Other_Sales": 0.38,
   "Global_Sales": 2.48,
   "Critic_Score": 92,
   "Critic_Count": 100,
   "User_Score": 8.6,
   "User_Count": 6383,
   "Developer": "From Software",
   "Rating": "M"
 },
 {
   "Name": "Halo 5: Guardians",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Shooter",
   "Publisher": "Microsoft Game Studios",
   "NA_Sales": 2.78,
   "EU_Sales": 1.27,
   "JP_Sales": 0.03,
   "Other_Sales": 0.41,
   "Global_Sales": 4.48,
   "Critic_Score": 84,
   "Critic_Count": 101,
   "User_Score": 6.4,
   "User_Count": 2438,
   "Developer": "343 Industries",
   "Rating": "T"
 },
 {
   "Name": "Rise of the Tomb Raider",
   "Platform": "XOne",
   "Year_of_Release": 2015,
   "Genre": "Adventure",
   "Publisher": "Square Enix",
   "NA_Sales": 0.55,
   "EU_Sales": 0.7,
   "JP_Sales": 0.02,
   "Other_Sales": 0.11,
   "Global_Sales": 1.38,
   "Critic_Score": 86,
   "Critic_Count": 102,
   "User_Score": 8,
   "User_Count": 1288,
   "Developer": "Crystal Dynamics",
   "Rating": "M"
 },
 {
   "Name": "Until Dawn",
   "Platform": "PS4",
   "Year_of_Release": 2015,
   "Genre": "Adventure",
   "Publisher": "Sony Computer Entertainment Europe",
   "NA_Sales": 0.45,
   "EU_Sales": 0.9,
   "JP_Sales": 0.05,
   "Other_Sales": 0.26,
   "Global_Sales": 1.66,
   "Critic_Score": 79,
   "Critic_Count": 103,
   "User_Score": 8.2,
   "User_Count": 2161,
   "Developer": "SuperMassive Games",
   "Rating": "M"
 }
]
